# Generated by Django 4.2.4 on 2023-09-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date updated'),
        ),
    ]
