# Generated by Django 4.2.5 on 2023-09-23 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_commentblogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentblogpost',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commentblogpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost'),
        ),
    ]
